name: nightly-ci

on:
   schedule:
    - cron: '01 1 * * *'

env:
 HOME: /root
 PYTHONUNBUFFERED: true
 CLUSTER: relocate
 NODES: 3
 PULLSECRET: /root/openshift_pull.json
 PARAMFILE: aicli_parameters.yml
 AI_OFFLINETOKEN: ${{ secrets.AI_OFFLINETOKEN }}

jobs:
    requirements:
      runs-on: libvirt
      steps:
       - uses: actions/checkout@v2
       - run: git pull origin ${GITHUB_REF##*/}
       - name: Install kcli
         run: |
           curl https://raw.githubusercontent.com/karmab/kcli/master/install.sh | bash
       - name: Install aicli
         run: |
           pip3 install -U assisted-service-client aicli
       - name: Clean up
         continue-on-error: true
         run: |
           kcli delete plan --yes $CLUSTER || true
           systemctl restart sushy

    deploy-kcli-plan:
      needs: requirements
      runs-on: libvirt
      steps:
      - name: Deploy kcli plan
        run: |
          kcli create plan -P nodes=$NODES $CLUSTER

    deploy-ai-cluster:
      needs: deploy-kcli-plan
      runs-on: libvirt
      steps:
      - name: Deploy ai cluster
        run: |
          aicli create deployment --pf $PARAMFILE -P pull_secret=$PULLSECRET $CLUSTER --force

    clean-up:
      needs: deploy-ai-cluster
      runs-on: libvirt
      steps:
      - name: Clean everything after success
        run: |
          kcli delete plan --yes $CLUSTER
